### PR TITLE
fix(pages/library): owned items logic

### LINKED ISSUE #21: "Analysing your library" stucked
When I select Library. it says "Analysing your library" and nothing happens.

### LINKED ISSUE #32: [bug] Crashes when trying to open.
image
After clicking on the Statistics button, the app has to reload, and nothing else works after that.

### PR DESCRIPTION
**Pull request by SunsetTechuila**
fixes #32 
fixes #21

### CODE REVIEW

File: src/pages/library.tsx [hunk 1]
```diff
@@ -94,6 +94,7 @@ const LibraryPage = () => {
 
         playlists.forEach(playlist => {
             if (playlist.totalLength === 0) return;
+            if (!playlist.ownedBySelf && indexOfFirstNotOwned !== -1) indexOfFirstNotOwned = playlistUris.length;
```
Comment (harbassan) [inline src/pages/library.tsx:97]: is this supposed to be `indexOfFirstNotOwned === -1` ?

Comment (SunsetTechuila) [reply src/pages/library.tsx]: Yes
